language: c
compiler:
  - clang
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq autoconf-archive
  - sudo apt-get install -qq libssl-dev libgsasl7-dev libdb-dev libpam0g-dev libmysqlclient-dev libpq-dev libldap2-dev libsqlite3-dev libidn11-dev libexpat1-dev libudns-dev check
before_script: autoreconf -fi
script: ./configure --enable-ssl --enable-mysql --enable-pgsql --enable-sqlite --enable-db --enable-ldap --enable-pam --enable-pipe --enable-anon --enable-fs --without-subst && make && make check
